server:
  google_maps:
    detailed_search_fields:
      - name
      - opening_hours
      - formatted_address
      - adr_address
      - url
      - user_ratings_total
  plan_solver:
    same_place_dedupe_count_limit: 2
    nearby_cities_count_limit: 3
