server:
  google_maps:
    detailed_search_fields:
      - name
      - opening_hours
      - formatted_address
      - adr_address
      - url
  solver_config:
    max_same_place_repeat: 4
    min_place_diversity: 5
