server:
  google_maps:
    detailed_search_fields:
      - name
      - opening_hours
      - formatted_address
      - adr_address
      - url
      - user_ratings_total
  plan_solver:
    SamePlaceDupCountLimit: 2